#ifndef TEXTTYPESLIBRARY
#define TEXTTYPESLIBRARY
enum QuadDrawType {DEFAULTQUAD = 0,ROUNDEDQUAD = 1,INVERTEDQUAD = 2, CIRCLEQUAD = 3, OUTLINEQUAD =4};
enum TextAlignment{TEXTALILEFT,TEXTALIRIGHT,TEXTALICENTER};
#endif
